feat!: change showYear to monthFormat
krystalcampioni/vue-hotel-datepicker pull request #249
Opened 2020-11-27 14:59 UTC by aaharu

Thank you for useful library.

In Japan, the month displayed as "January 2020" is displayed as "2020年1月".
So `showYear` is not suitable in some languages.

What do you think of this change?

2020-11-28 16:50 UTC, matiasperrone commented
I think that we should add "monthFormat", but do not remove "showYear" to mantain backwards compatibility.
Although it could be marked as "deprecated", but I don't think so.

2020-11-29 11:44 UTC, superbiche requested changes
Thanks for the contribution. A couple enhancements but I like it

2020-11-29 11:44 UTC, superbiche commented on README.md
> +The month format string.
Maybe add a line to explain this also replaces `showYear`

2020-11-29 11:44 UTC, superbiche commented on src/App.vue
> +                <DatePicker :alwaysVisible="true" monthFormat="MMMM YYYY" :i18n="i18n" />
As it's the default, it would be better to remove the monthFormat prop (to avoid confusion, let users understand it's the default format)

2020-11-29 11:47 UTC, superbiche commented
> I think that we should add "monthFormat", but do not remove "showYear" to mantain backwards compatibility.
> Although it could be marked as "deprecated", but I don't think so.

@matiasperrone as it's targeted to v4.0, we can break BC and remove `showYear`, as the approach @aaharu suggests is more flexible and tackles both the showYear toggle and the custom format. 
Anyway we're already breaking BC in v4.0 so,

2020-12-02 11:02 UTC, aaharu commented
Thanks for reviewing. I added the explains to migrate showYear

2020-12-04 10:58 UTC, superbiche approved these changes
LGTM

2020-12-09 09:55 UTC, superbiche commented
@aaharu hey, any reason it's still a Draft? It's good to merge if you ask me, just need you to remove the Draft status if you also consider it ready. @matiasperrone feel free to let me know what you think if you had time to review it

2020-12-09 14:20 UTC, matiasperrone commented
I'm going to check this out and do the merge...
I need a couple of days

2021-01-12 02:09 UTC, matiasperrone commented
Now a lot of time passed since last time I checked this issue.
I think that I can find a compromise solution a possible mixed solution with back compatibility.

2021-01-14 18:43 UTC, matiasperrone commented
I'll be adding a `yearBeforeMonth` variable in v4.1 in order to achieve this behavior

2021-01-14 18:43 UTC, closed without merging